name: test

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
      - name: Setup
        run: poetry install --all-extras
      - name: Run tests
        run: poetry run python -u -m unittest discover
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Test Spark Connect
        run: |
          sh run_spark_connect.sh
          poetry run python -m unittest tests/test_spark_connect.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SPARK_CONNECT_MODE_ENABLE: 1
